#pragma once

#define __ENUMERATE_TOKEN_TYPES             \
	__ENUMERATE(AMPERSAND)                  \
	__ENUMERATE(AMPERSAND_AMPERSAND)        \
	__ENUMERATE(AMPERSAND_AMPERSAND_EQUALS) \
	__ENUMERATE(AMPERSAND_EQUALS)           \
	__ENUMERATE(ASTERISK)                   \
	__ENUMERATE(ASTERISK_ASTERISK)          \
	__ENUMERATE(ASTERISK_ASTERISK_EQUALS)   \
	__ENUMERATE(ASTERISK_EQUALS)            \
	__ENUMERATE(BACKSLASH)                  \
	__ENUMERATE(CARET)                      \
	__ENUMERATE(CARET_EQUALS)               \
	__ENUMERATE(COLON)                      \
	__ENUMERATE(COLON_COLON)                \
	__ENUMERATE(COMMA)                      \
	__ENUMERATE(DEFAULT)                    \
	__ENUMERATE(DOT)                        \
	__ENUMERATE(DOT_DOT)                    \
	__ENUMERATE(DOT_DOT_DOT)                \
	__ENUMERATE(ELSE)                       \
	__ENUMERATE(EOF)                        \
	__ENUMERATE(EQUALS)                     \
	__ENUMERATE(EQUALS_EQUALS)              \
	__ENUMERATE(EQUALS_GREATER)             \
	__ENUMERATE(EXCLAMATION)                \
	__ENUMERATE(EXCLAMATION_EQUALS)         \
	__ENUMERATE(FALSE)                      \
	__ENUMERATE(FOR)                        \
	__ENUMERATE(FUNCTION)                   \
	__ENUMERATE(GLYPH)                      \
	__ENUMERATE(GREATER)                    \
	__ENUMERATE(GREATER_EQUALS)             \
	__ENUMERATE(GREATER_GREATER)            \
	__ENUMERATE(GREATER_GREATER_EQUALS)     \
	__ENUMERATE(IDENTIFIER)                 \
	__ENUMERATE(IF)                         \
	__ENUMERATE(LEFT_BRACE)                 \
	__ENUMERATE(LEFT_BRACKET)               \
	__ENUMERATE(LEFT_PARENTHESIS)           \
	__ENUMERATE(LESS)                       \
	__ENUMERATE(LESS_EQUALS)                \
	__ENUMERATE(LESS_EQUALS_GREATER)        \
	__ENUMERATE(LESS_LESS)                  \
	__ENUMERATE(LESS_LESS_EQUALS)           \
	__ENUMERATE(MATCH)                      \
	__ENUMERATE(MINUS)                      \
	__ENUMERATE(MINUS_EQUALS)               \
	__ENUMERATE(MINUS_MINUS)                \
	__ENUMERATE(NULL)                       \
	__ENUMERATE(NUMBER)                     \
	__ENUMERATE(PERCENT)                    \
	__ENUMERATE(PERCENT_EQUALS)             \
	__ENUMERATE(PIPE)                       \
	__ENUMERATE(PIPE_EQUALS)                \
	__ENUMERATE(PIPE_PIPE)                  \
	__ENUMERATE(PIPE_PIPE_EQUALS)           \
	__ENUMERATE(PLUS)                       \
	__ENUMERATE(PLUS_EQUALS)                \
	__ENUMERATE(PLUS_PLUS)                  \
	__ENUMERATE(QUESTION)                   \
	__ENUMERATE(QUESTION_COLON)             \
	__ENUMERATE(QUESTION_DOT)               \
	__ENUMERATE(QUESTION_QUESTION)          \
	__ENUMERATE(QUESTION_QUESTION_EQUALS)   \
	__ENUMERATE(RETURN)                     \
	__ENUMERATE(RIGHT_BRACE)                \
	__ENUMERATE(RIGHT_BRACKET)              \
	__ENUMERATE(RIGHT_PARENTHESIS)          \
	__ENUMERATE(SEMICOLON)                  \
	__ENUMERATE(SLASH)                      \
	__ENUMERATE(SLASH_EQUALS)               \
	__ENUMERATE(STRING)                     \
	__ENUMERATE(TILDE)                      \
	__ENUMERATE(TRUE)                       \
	__ENUMERATE(UNKNOWN)                    \
	__ENUMERATE(VAR)                        \
	__ENUMERATE(WHILE)

